apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefiles-standard
provisioner: kubernetes.io/azure-file
reclaimPolicy: Retain
mountOptions:
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_ZRS